name: Deploy Firebase Functions to DEV

on:
  push:
    branches:
      - develop
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Change node current to node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup project for environment current
        run: |
          ls -a
          echo "Install dependecies"
          npm install
          node deploy.js --secretKeyJwt=${{ secrets.secretKeyJwtDEV }} --bigqueryProjectName=${{ secrets.bigqueryProjectNameDEV }} --serviceAccountKeyUrl="${{ secrets.serviceAccountKeyUrlDEV }}"

      - name: Download files
        run: |
          cd ..
          sudo apt install curl
          curl "${{ secrets.firebaseRcUrlDEV }}" -o .firebaserc
          curl "${{ secrets.firebaseJsonUrlDEV }}" -o firebase.json
          ls -a

      - name: Start deploy
        run: |
          cd ..
          mv ./${{ github.event.repository.name }} ./functions
          npm install -g firebase-tools
          firebase deploy --only functions --token "${{ secrets.tokenAuthFirebaseDEV }}"
          echo "Post Deploy"
          mv ./functions ./${{ github.event.repository.name }}